server:
  port: 8000

spring:
  application:
    name: service-discovery

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry:  false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    region: default